<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Icons\keys.ico</ApplicationIcon>
    <Version>0.0.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Fonts\Dongle\Dongle-Bold.ttf" />
    <None Remove="Fonts\Dongle\Dongle-Light.ttf" />
    <None Remove="Fonts\Dongle\Dongle-Regular.ttf" />
    <None Remove="Fonts\Inter\Inter-Black.ttf" />
    <None Remove="Fonts\Inter\Inter-Bold.ttf" />
    <None Remove="Fonts\Inter\Inter-Medium.ttf" />
    <None Remove="Fonts\Inter\Inter-Regular.ttf" />
    <None Remove="Fonts\Inter\Inter-Thin.ttf" />
    <None Remove="Fonts\password.ttf" />
    <None Remove="Icons\close\white.png" />
    <None Remove="Icons\copy\black.png" />
    <None Remove="Icons\copy\white.png" />
    <None Remove="Icons\keys.ico" />
    <None Remove="Icons\keys.png" />
    <None Remove="Icons\lock.png" />
    <None Remove="Icons\lock\black.png" />
    <None Remove="Icons\lock\white.png" />
    <None Remove="Icons\minimize\white.png" />
    <None Remove="Icons\plus\black.png" />
    <None Remove="Icons\plus\white.png" />
    <None Remove="Icons\search.png" />
    <None Remove="Icons\settings\black.png" />
    <None Remove="Icons\settings\white.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DevExpressMvvm" Version="22.1.3" />
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="1.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="PropertyChanging.Fody" Version="1.30.3" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\Dongle\Dongle-Bold.ttf" />
    <Resource Include="Fonts\Dongle\Dongle-Light.ttf" />
    <Resource Include="Fonts\Dongle\Dongle-Regular.ttf" />
    <Resource Include="Fonts\Inter\Inter-Black.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Inter\Inter-Bold.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Inter\Inter-Medium.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Inter\Inter-Regular.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Inter\Inter-Thin.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\password.ttf" />
    <Resource Include="Icons\close\white.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\copy\black.png" />
    <Resource Include="Icons\copy\white.png" />
    <Resource Include="Icons\keys.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\keys.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\lock.png" />
    <Resource Include="Icons\lock\black.png" />
    <Resource Include="Icons\lock\white.png" />
    <Resource Include="Icons\minimize\white.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\plus\black.png" />
    <Resource Include="Icons\plus\white.png" />
    <Resource Include="Icons\search.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\settings\black.png" />
    <Resource Include="Icons\settings\white.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Security\" />
  </ItemGroup>

</Project>
